apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-hexagonal-template
  labels:
    app: ktor-hexagonal-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-hexagonal-template
  template:
    metadata:
      labels:
        app: ktor-hexagonal-template
    spec:
      initContainers:
        - name: ktor-hexagonal-template-postgresql-init
          image: busybox
          command: [ 'sh', '-c', 'echo -e "Checking for the availability of Postgresql Server deployment"; while ! nc -z ktor-hexagonal-template-postgresql 5432; do sleep 1; printf "-"; done; echo -e "  >> Postgresql DB Server has started";' ]
      containers:
        - name: ktor-hexagonal-template
          image: ktor-hexagonal-template:0.0.1
          envFrom:
            - configMapRef:
                name: ktor-hexagonal-template
            - secretRef:
                name: ktor-hexagonal-template
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 30
            periodSeconds: 1
          ports:
            - containerPort: 8080
