apiVersion: v1
kind: Secret
metadata:
  name: ktor-hexagonal-template
type: Opaque
data:
  KTOR_DATASOURCE_USERNAME : cm9vdA==
  KTOR_DATASOURCE_PASSWORD : cGFzc3dvcmQ=
  POSTGRES_USER: cm9vdA==
  PGUSER: cm9vdA==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=